# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1466, 780)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.Image1 = PlotWidget(self.centralwidget)
        self.Image1.setStyleSheet("")
        self.Image1.setObjectName("Image1")
        self.Image1.hideAxis('bottom')
        self.Image1.hideAxis('left')
        self.Image1.setBackground('w')
        self.gridLayout.addWidget(self.Image1, 1, 0, 1, 1)
        self.Image2 = PlotWidget(self.centralwidget)
        self.Image2.setObjectName("Image2")
        self.Image2.hideAxis('bottom')
        self.Image2.hideAxis('left')
        self.Image2.setBackground('w')
        self.gridLayout.addWidget(self.Image2, 1, 1, 1, 1)
        self.IMAGECOMB1 = QtWidgets.QComboBox(self.centralwidget)
        self.IMAGECOMB1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.IMAGECOMB1.setObjectName("IMAGECOMB1")
        self.IMAGECOMB1.addItem("")
        self.IMAGECOMB1.addItem("")
        self.IMAGECOMB1.addItem("")
        self.IMAGECOMB1.addItem("")
        self.IMAGECOMB1.addItem("")
        self.gridLayout.addWidget(self.IMAGECOMB1, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.Output1 = PlotWidget(self.centralwidget)
        self.Output1.setStyleSheet("")
        self.Output1.setObjectName("Output1")
        self.Output1.hideAxis('bottom')
        self.Output1.hideAxis('left')
        self.Output1.setBackground('w')
        self.gridLayout_4.addWidget(self.Output1, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 1, 1, 1)
        self.OutPut2 = PlotWidget(self.centralwidget)
        self.OutPut2.setObjectName("OutPut2")
        self.OutPut2.hideAxis('bottom')
        self.OutPut2.hideAxis('left')
        self.OutPut2.setBackground('w')
        self.gridLayout_4.addWidget(self.OutPut2, 4, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("color: rgb(85, 0, 255);\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.OUTOPTION = QtWidgets.QComboBox(self.groupBox)
        self.OUTOPTION.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.OUTOPTION.setObjectName("OUTOPTION")
        self.OUTOPTION.addItem("")
        self.OUTOPTION.addItem("")
        self.OUTOPTION.addItem("")
        self.gridLayout_3.addWidget(self.OUTOPTION, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.Comb11 = QtWidgets.QComboBox(self.groupBox)
        self.Comb11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.Comb11.setObjectName("Comb11")
        self.Comb11.addItem("")
        self.Comb11.addItem("")
        self.gridLayout_3.addWidget(self.Comb11, 1, 1, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_3.addWidget(self.horizontalSlider, 1, 2, 1, 1)
        self.COMB1 = QtWidgets.QComboBox(self.groupBox)
        self.COMB1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.COMB1.setObjectName("COMB1")
        self.COMB1.addItem("")
        self.COMB1.addItem("")
        self.COMB1.addItem("")
        self.COMB1.addItem("")
        self.COMB1.addItem("")
        self.COMB1.addItem("")
        self.COMB1.addItem("")
        self.gridLayout_3.addWidget(self.COMB1, 2, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.Comb21 = QtWidgets.QComboBox(self.groupBox)
        self.Comb21.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.Comb21.setObjectName("Comb21")
        self.Comb21.addItem("")
        self.Comb21.addItem("")
        self.gridLayout_3.addWidget(self.Comb21, 3, 1, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout_3.addWidget(self.horizontalSlider_2, 3, 2, 1, 1)
        self.Comb22 = QtWidgets.QComboBox(self.groupBox)
        self.Comb22.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.Comb22.setObjectName("Comb22")
        self.Comb22.addItem("")
        self.Comb22.addItem("")
        self.Comb22.addItem("")
        self.Comb22.addItem("")
        self.Comb22.addItem("")
        self.Comb22.addItem("")
        self.Comb22.addItem("")
        self.gridLayout_3.addWidget(self.Comb22, 4, 1, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 2)
        # self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton.setObjectName("pushButton")
        # self.gridLayout_4.addWidget(self.pushButton, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 1, 2, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.IMAGECOMB2 = QtWidgets.QComboBox(self.centralwidget)
        self.IMAGECOMB2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.IMAGECOMB2.setObjectName("IMAGECOMB2")
        self.IMAGECOMB2.addItem("")
        self.IMAGECOMB2.addItem("")
        self.IMAGECOMB2.addItem("")
        self.IMAGECOMB2.addItem("")
        self.IMAGECOMB2.addItem("")
        self.gridLayout_2.addWidget(self.IMAGECOMB2, 0, 1, 1, 1)
        self.Image3 = PlotWidget(self.centralwidget)
        self.Image3.setObjectName("Image3")
        self.Image3.hideAxis('bottom')
        self.Image3.hideAxis('left')
        self.Image3.setBackground('w')
        self.gridLayout_2.addWidget(self.Image3, 1, 0, 1, 1)
        self.Image4 = PlotWidget(self.centralwidget)
        self.Image4.setObjectName("Image4")
        self.Image4.hideAxis('bottom')
        self.Image4.hideAxis('left')
        self.Image4.setBackground('w')
        self.gridLayout_2.addWidget(self.Image4, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1466, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_Image_1 = QtWidgets.QAction(MainWindow)
        self.actionImport_Image_1.setObjectName("actionImport_Image_1")
        self.actionImport_Image_2 = QtWidgets.QAction(MainWindow)
        self.actionImport_Image_2.setObjectName("actionImport_Image_2")
        self.menuFile.addAction(self.actionImport_Image_1)
        self.menuFile.addAction(self.actionImport_Image_2)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Image 1"))
        self.IMAGECOMB1.setItemText(0,_translate("", ""))
        self.IMAGECOMB1.setItemText(1, _translate("MainWindow", "MAGNITUDE"))
        self.IMAGECOMB1.setItemText(2, _translate("MainWindow", "PHASE"))
        self.IMAGECOMB1.setItemText(3, _translate("MainWindow", "REAL"))
        self.IMAGECOMB1.setItemText(4, _translate("MainWindow", "IMAGINARY"))
        self.label_3.setText(_translate("MainWindow", "Output1"))
        self.label_4.setText(_translate("MainWindow", "Output2"))
        self.groupBox.setTitle(_translate("MainWindow", "MIXER OUTPUT TO:"))
        self.OUTOPTION.setItemText(0, _translate("", ""))
        self.OUTOPTION.setItemText(1, _translate("MainWindow", "OUTPUT 1"))
        self.OUTOPTION.setItemText(2, _translate("MainWindow", "OUTPUT 2"))
        self.label_7.setText(_translate("MainWindow", "Component 1:"))
        self.Comb11.setItemText(0, _translate("MainWindow", "Image 1"))
        self.Comb11.setItemText(1, _translate("MainWindow", "Image 2"))
        self.COMB1.setItemText(0, _translate("MainWindow", ""))
        self.COMB1.setItemText(1, _translate("MainWindow", "MAGNITUDE"))
        self.COMB1.setItemText(2, _translate("MainWindow", "PHASE"))
        self.COMB1.setItemText(3, _translate("MainWindow", "REAL"))
        self.COMB1.setItemText(4, _translate("MainWindow", "IMAGINARY"))
        self.COMB1.setItemText(5, _translate("MainWindow", "UNIT PHASE"))
        self.COMB1.setItemText(6, _translate("MainWindow", "UNIT MAGNITUDE"))
        self.label_8.setText(_translate("MainWindow", "Component 2:"))
        self.Comb21.setItemText(0, _translate("MainWindow", "Image 1"))
        self.Comb21.setItemText(1, _translate("MainWindow", "Image 2"))
        self.Comb22.setItemText(0, _translate("MainWindow", ""))
        self.Comb22.setItemText(1, _translate("MainWindow", "MAGNITUDE"))
        self.Comb22.setItemText(2, _translate("MainWindow", "PHASE"))
        self.Comb22.setItemText(3, _translate("MainWindow", "REAL "))
        self.Comb22.setItemText(4, _translate("MainWindow", "IMAGINARY"))
        self.Comb22.setItemText(5, _translate("MainWindow", "UNIT PHASE"))
        self.Comb22.setItemText(6, _translate("MainWindow", "UNIT MAGNITUDE "))
        # self.pushButton.setText(_translate("MainWindow", "MIX"))
        self.label_2.setText(_translate("MainWindow", "Image 2"))
        self.IMAGECOMB2.setItemText(1, _translate("MainWindow", "MAGNITUDE"))
        self.IMAGECOMB2.setItemText(2, _translate("MainWindow", "PHASE"))
        self.IMAGECOMB2.setItemText(3, _translate("MainWindow", "REAL"))
        self.IMAGECOMB2.setItemText(4, _translate("MainWindow", "IMAGINARY"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionImport_Image_1.setText(_translate("MainWindow", "Import Image 1"))
        self.actionImport_Image_2.setText(_translate("MainWindow", "Import Image 2"))

from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
