# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(11, 41, 761, 501))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.BrowseS1 = QtWidgets.QPushButton(self.widget)
        self.BrowseS1.setObjectName("BrowseS1")
        self.verticalLayout.addWidget(self.BrowseS1)
        self.BrowseS2 = QtWidgets.QPushButton(self.widget)
        self.BrowseS2.setObjectName("BrowseS2")
        self.verticalLayout.addWidget(self.BrowseS2)
        self.Mixer = QtWidgets.QPushButton(self.widget)
        self.Mixer.setObjectName("Mixer")
        self.verticalLayout.addWidget(self.Mixer)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.MixSlider = QtWidgets.QSlider(self.widget)
        self.MixSlider.setOrientation(QtCore.Qt.Horizontal)
        self.MixSlider.setObjectName("MixSlider")
        self.gridLayout.addWidget(self.MixSlider, 0, 1, 1, 1)
        self.Table = QtWidgets.QTableWidget(self.widget)
        self.Table.setObjectName("Table")
        self.Table.setColumnCount(3)
        self.Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.Table, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BrowseS1.setText(_translate("MainWindow", "Broswse Song1"))
        self.BrowseS2.setText(_translate("MainWindow", "Broswse Song2"))
        self.Mixer.setText(_translate("MainWindow", "Mix"))
        item = self.Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Similarty"))
        item = self.Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Similarty C2"))
        item = self.Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Similarty C3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
